version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: monthly
      time: "04:00"
      timezone: America/New_York
    open-pull-requests-limit: 5
    assignees:
      - bradsjm
    versioning-strategy: increase

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
      time: "04:00"
      timezone: America/New_York
    open-pull-requests-limit: 5
    assignees:
      - bradsjm
