export enum ArmingStateType {
    AWAY_EXIT_DELAY = "ARM-AWAY-EXIT-DELAY",
    STAY_EXIT_DELAY = "ARM-STAY-EXIT-DELAY",
    ENTRY_DELAY = "ENTRY_DELAY",
    EXIT_DELAY = "EXIT_DELAY",
    DISARM = "DISARM",
    ARM_STAY = "ARM_STAY",
    ARM_AWAY = "ARM_AWAY"
}
